### ISSUE TITLE
iq 2

### ISSUE THREAD

**Issue by Aethusx** [iUnixPL/Hayato#1]
https://github.com/iUnixPL/Hayato/blob/92ec485e5add1b154df23e61ed225781df37de2f/src/main/java/net/unix/hayato/core/basic/HayatoImpl.java#L42

iq 2

**Comment by vocan** [comment]
popieram przedmuwce

**Comment by iUnixPL** [comment]
skid

**Comment by vocan** [comment]
natalia kocham cie prosze odpisz

**Comment by vocan** [comment]
no szmato odpisz bo sie tam przejde

**Comment by vocan** [comment]
przejebalas sobie natalia to koniec

**Comment by vocan** [comment]
X D !
